updated cli

diff --git a/bin/.kic/commands/cluster/create b/bin/.kic/commands/cluster/create
--- a/bin/.kic/commands/cluster/create
+++ b/bin/.kic/commands/cluster/create
@@ -7,14 +7,14 @@
 # cd "$(dirname "${BASH_SOURCE[0]}")" || exit
 
 # validate directories
-if [ ! -f "$REPO_BASE/inner-loop/k3d.yaml" ]; then echo "File not found - \"$REPO_BASE\"/inner-loop/k3d.yaml"; exit 1; fi
+if [ ! -f "$REPO_BASE/.devcontainer/k3d.yaml" ]; then echo "File not found - \"$REPO_BASE\"/.devcontainer/k3d.yaml"; exit 1; fi
 
 "$(dirname "${BASH_SOURCE[0]}")/delete"
 
 echo ""
 echo "Creating cluster ..."
 
-k3d cluster create --registry-use k3d-registry.localhost:5500 --config "$REPO_BASE/inner-loop/k3d.yaml"
+k3d cluster create --registry-use k3d-registry.localhost:5500 --config "$REPO_BASE/.devcontainer/k3d.yaml"
 kubectl wait node --for condition=ready --all --timeout=30s
 sleep 10
 kubectl wait pod -l k8s-app=kube-dns -n kube-system --for condition=ready --timeout 30s
diff --git a/bin/.kic/commands/cluster/deploy b/bin/.kic/commands/cluster/deploy
--- a/bin/.kic/commands/cluster/deploy
+++ b/bin/.kic/commands/cluster/deploy
@@ -9,27 +9,22 @@
 # validate directories
 if [ ! -d ./deploy ]; then echo "./deploy directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/webv ]; then echo "./deploy/webv directory not found. Please cd to an appropriate directory"; exit 1; fi
-if [ ! -d ./deploy/app ]; then echo "./deploy/app directory not found. Please cd to an appropriate directory"; exit 1; fi
+if [ ! -d ./deploy/imdb ]; then echo "./deploy/imdb directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/bootstrap ]; then echo "./deploy/bootstrap directory not found. Please cd to an appropriate directory"; exit 1; fi
 
-# build the app
-"$(dirname "${BASH_SOURCE[0]}")/../app/build"
-
-# create namespaces
+# create namespace
 kubectl apply -f deploy
-kubectl apply -f deploy/bootstrap
 
-# deploy app reference app
-kubectl apply -f deploy/app
+# deploy imdb reference app
+kubectl apply -f deploy/imdb
 
-# deploy prometheus, grafana, and fluent bit
+# deploy heartbeat, prometheus, grafana, and fluent bit
 kubectl apply -f deploy/bootstrap
 kubectl apply -R -f deploy/bootstrap
 
-# deploy jumpbox
 "$(dirname "${BASH_SOURCE[0]}")/jumpbox"
 
 # deploy WebV after the app starts
-kubectl wait pod -l app=csapp -n csapp --for condition=ready --timeout=60s
+kubectl wait pod -l app=imdb -n imdb --for condition=ready --timeout=60s
 
 kubectl apply -f deploy/webv
